### PR TITLE
Ease new board setup and send comment notifications

### PR DESCRIPTION
**Pull request by svvitale**
Probably easiest to review this commit-by-commit - the whole thing ended up being quite a few lines.

Two goals:
* Make setting up a new submissions board easy by autocreating lists and labels, and pulling the needed list IDs into the local database.  I used this code to set up a "Submissions-dev" board, and I think it will also help some of our guinea pig meetup brethren do the same.
* Notify submitters of card comments.  Allow them to reply to the notification to post a comment reply.

One hack:
* To get the "card email" from Trello (which is required for the 2nd bullet above), I had to do some browser emulation using the actual username and password for the Organizers account 🤢.  See 9d239f5.

### CODE REVIEW

**Comment by svvitale** [comment]
FYI, this will require a database migration.  I just looked at Flask-Migrate and it seems like it'd be easiest to implement it in its own branch, merge to develop, and then pull into this PR.  Thoughts?

**Comment by frankV** [comment]
that's what I figured. I've got some experience with it... happy to pair on
this with you if ya want

**Comment by svvitale** [comment]
Sure, if you've got bandwidth for it.  Depending on what time we wrap up tonight, maybe we could knock it out.

**Review by frankV — DISMISSED** [review]
bravo 👏

**Review by frankV — APPROVED** [review]

**Pull request merged**
